Select
codefield-nl/briq pull request #7
Opened 2021-02-12 10:31 UTC by danielgroen

select button fixed

2021-02-12 20:19 UTC, KoenZwijnenburg requested changes

2021-02-12 20:19 UTC, KoenZwijnenburg commented on projects/briq/src/lib/form-components/form-elements/select/select-builder.ts
> +    this.defaultValue = defaultValue;
Het is denk ik wel verstandig om ook de value in de FormControl te zetten als je een default value meegeeft. Anders wordt hij niet meegestuurd als je het formulier direct submit (en dit veld niet handmatig wijzigt).

2021-02-12 20:19 UTC, KoenZwijnenburg commented on projects/briq/src/lib/form-components/form-elements/select/select.component.scss
> +            transition: transform $speed $cubic-bezir;
ng-deep wil je eigenlijk zoveel mogelijk vermijden. 

https://dev.to/jwp/angular-10-ng-deep-and-host-pseudo-classes-1kbg#:~:text=Angular's%20API%20states%20that%20the,deep%20psuedo%2Dclass%20is%20deprecated.&text=completely%20disables%20view%2Dencapsulation%20for,global%2C%20not%20a%20good%20thing.&text=Angular%20doesn't%20find%20it%20when%20the%20depth%20is%20deep.

2021-02-13 08:34 UTC, danielgroen commented on projects/briq/src/lib/form-components/form-elements/select/select.component.scss
> +            transition: transform $speed $cubic-bezir;
hm ja check, maar dus ook niet in dit geval? gezien er een transition op de rotatie zit van de chevron, dat is alleen voor de select element nodig

2021-02-13 08:35 UTC, danielgroen commented on projects/briq/src/lib/form-components/form-elements/select/select-builder.ts
> +    this.defaultValue = defaultValue;
Heb dit inderdaad herschreven in mijn huidige branch want ik kwam hier ook achter!

2021-02-13 08:37 UTC, danielgroen commented on projects/briq/src/lib/form-components/form-elements/select/select.component.spec.ts
> +import { ComponentFixture, TestBed } from '@angular/core/testing';
Eens!

Dit zijn de default tests en heb hier nog niks mee gedaan, wat raad jij hier in aan? Eerst weg laten en wellicht later tests toevoegen?

2021-02-13 08:38 UTC, danielgroen commented on src/app/app.component.ts
> +      {value: '1', label: '1' },
Bedoel je hiermee dat we .setLabel() weghalen en deze in de constructor van de form elements zetten als 3e parameter?

2021-02-16 10:44 UTC, closed without merging