fixes after the pr of branch "checkbox"
codefield-nl/briq pull request #9
Opened 2021-02-18 14:20 UTC by danielgroen

2021-02-18 15:31 UTC, KoenZwijnenburg requested changes

2021-02-18 15:31 UTC, KoenZwijnenburg commented on projects/briq/src/lib/form-components/shared/label-value.ts
> +  constructor(public value:BriqIdentifier, label: BriqIdentifier, public disabled?: boolean) {
Identifier zou ik alleen gebruiken voor ID's. Het idee van de BriqIdentifier is dat we alle elemenent een ID kunnen meegeven deze is in principe niet van toepassing voor de gebruikers, alleen voor de devs.  Ik heb gekozen voor een apart type BriqIdentifer, omdat je dan in een keer alle types voor de Identifier kan aanpassen.  Dat het type toevallig string | number is, betekent niet dat dit altijd zo blijft.

Types zijn er ook voornamelijk om de developers een instructie te geven hoe het Object eruit moet zien, hierbij is het belangrijk om alleen herbruikbare types te gebruiken als ze echt dezelfde use case hebben.

Dus als je voor value ook type number | string wilt gebruiken dan moet je daar alsnog een ander type voor aanmaken. Anders raak je op een gegeven moment in de knel als je BriqIdentifier op 100 plekken gebruikt en je wilt toevallig een van de 100 use-cases  aanpassen.

Bovendien vraag ik me af of het type string | number wel altijd voldoende is voor een value. Het zou net zo goed een array of object kunnen zijn. In zulke gevallen mag je best een keer type any zetten.

2021-02-18 16:36 UTC, danielgroen commented on projects/briq/src/lib/form-components/shared/label-value.ts
> +  constructor(public value:BriqIdentifier, label: BriqIdentifier, public disabled?: boolean) {
Klinkt legit!

Ik stel dan voor dat we voor als nog type "string" en "number" gebruiken en dat we pas over gaan type naar any als we er op stuklopen doordat het scenario voordoet dat de value een boolean is oid.

2021-02-19 10:07 UTC, KoenZwijnenburg commented on projects/briq/src/lib/form-components/shared/label-value.ts
> +  constructor(public value:BriqIdentifier, label: BriqIdentifier, public disabled?: boolean) {
Lijkt me prima!

2021-02-22 13:04 UTC, closed without merging